// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WarehouseEFApp.Context;

#nullable disable

namespace WarehouseEFApp.Migrations
{
    [DbContext(typeof(WarehouseDbContext))]
    [Migration("20251128094614_AddPersonEmail")]
    partial class AddPersonEmail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "gender_enum", new[] { "M", "F", "O" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "transaction_type_enum", new[] { "DELIVERY", "SHIPPING", "TRANSFER" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WarehouseEFApp.Models.Availability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("availability_pkey");

                    b.HasIndex("WarehouseId");

                    b.HasIndex(new[] { "ProductId", "WarehouseId" }, "availability_unique")
                        .IsUnique();

                    b.ToTable("availability", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("category_pkey");

                    b.HasIndex(new[] { "Name" }, "category_name_key")
                        .IsUnique();

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.DeliveryDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DeliveryDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("delivery_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int?>("Supplier")
                        .HasColumnType("integer")
                        .HasColumnName("supplier");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("delivery_document_pkey");

                    b.HasIndex("Supplier");

                    b.HasIndex("WarehouseId");

                    b.ToTable("delivery_document", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("Position")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("position");

                    b.HasKey("Id")
                        .HasName("person_pkey");

                    b.ToTable("person", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateOnly>("DateAdded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("date_added")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("product_pkey");

                    b.HasIndex("CategoryId");

                    b.HasIndex(new[] { "Name", "CategoryId" }, "product_name_cat_unique")
                        .IsUnique();

                    b.ToTable("product", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.ShippingDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("Recipient")
                        .HasColumnType("integer")
                        .HasColumnName("recipient");

                    b.Property<DateOnly>("ShippingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("shipping_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("shipping_document_pkey");

                    b.HasIndex("Recipient");

                    b.HasIndex("WarehouseId");

                    b.ToTable("shipping_document", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.TransactionLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(12, 3)
                        .HasColumnType("numeric(12,3)")
                        .HasColumnName("quantity");

                    b.Property<int>("TransactionId")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    b.HasKey("Id")
                        .HasName("transaction_line_pkey");

                    b.HasIndex("ProductId");

                    b.ToTable("transaction_line", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.TransferDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int>("ReceivingWarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("receiving_warehouse_id");

                    b.Property<int>("SourceWarehouseId")
                        .HasColumnType("integer")
                        .HasColumnName("source_warehouse_id");

                    b.Property<DateOnly>("TransferDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasColumnName("transfer_date")
                        .HasDefaultValueSql("CURRENT_DATE");

                    b.HasKey("Id")
                        .HasName("transfer_document_pkey");

                    b.HasIndex("ReceivingWarehouseId");

                    b.HasIndex("SourceWarehouseId");

                    b.ToTable("transfer_document", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.VProductMovementAnalysis", b =>
                {
                    b.Property<string>("CategoryName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category_name");

                    b.Property<decimal?>("CriticalDeliveriesQty")
                        .HasColumnType("numeric")
                        .HasColumnName("critical_deliveries_qty");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer")
                        .HasColumnName("product_id");

                    b.Property<string>("ProductName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("product_name");

                    b.Property<decimal?>("TotalDelivered")
                        .HasColumnType("numeric")
                        .HasColumnName("total_delivered");

                    b.Property<decimal?>("TotalShipped")
                        .HasColumnType("numeric")
                        .HasColumnName("total_shipped");

                    b.ToTable((string)null);

                    b.ToView("v_product_movement_analysis", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Warehouse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("ResponsiblePersonId")
                        .HasColumnType("integer")
                        .HasColumnName("responsible_person_id");

                    b.HasKey("Id")
                        .HasName("warehouse_pkey");

                    b.HasIndex("ResponsiblePersonId");

                    b.HasIndex(new[] { "Name" }, "warehouse_name_key")
                        .IsUnique();

                    b.ToTable("warehouse", (string)null);
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Availability", b =>
                {
                    b.HasOne("WarehouseEFApp.Models.Product", "Product")
                        .WithMany("Availabilities")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("availability_product_id_fkey");

                    b.HasOne("WarehouseEFApp.Models.Warehouse", "Warehouse")
                        .WithMany("Availabilities")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("availability_warehouse_id_fkey");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.DeliveryDocument", b =>
                {
                    b.HasOne("WarehouseEFApp.Models.Person", "SupplierNavigation")
                        .WithMany("DeliveryDocuments")
                        .HasForeignKey("Supplier")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("delivery_document_supplier_fkey");

                    b.HasOne("WarehouseEFApp.Models.Warehouse", "Warehouse")
                        .WithMany("DeliveryDocuments")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("delivery_document_warehouse_id_fkey");

                    b.Navigation("SupplierNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Product", b =>
                {
                    b.HasOne("WarehouseEFApp.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("product_category_id_fkey");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.ShippingDocument", b =>
                {
                    b.HasOne("WarehouseEFApp.Models.Person", "RecipientNavigation")
                        .WithMany("ShippingDocuments")
                        .HasForeignKey("Recipient")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("shipping_document_recipient_fkey");

                    b.HasOne("WarehouseEFApp.Models.Warehouse", "Warehouse")
                        .WithMany("ShippingDocuments")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("shipping_document_warehouse_id_fkey");

                    b.Navigation("RecipientNavigation");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.TransactionLine", b =>
                {
                    b.HasOne("WarehouseEFApp.Models.Product", "Product")
                        .WithMany("TransactionLines")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transaction_line_product_id_fkey");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.TransferDocument", b =>
                {
                    b.HasOne("WarehouseEFApp.Models.Warehouse", "ReceivingWarehouse")
                        .WithMany("TransferDocumentReceivingWarehouses")
                        .HasForeignKey("ReceivingWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transfer_document_receiving_warehouse_id_fkey");

                    b.HasOne("WarehouseEFApp.Models.Warehouse", "SourceWarehouse")
                        .WithMany("TransferDocumentSourceWarehouses")
                        .HasForeignKey("SourceWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("transfer_document_source_warehouse_id_fkey");

                    b.Navigation("ReceivingWarehouse");

                    b.Navigation("SourceWarehouse");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Warehouse", b =>
                {
                    b.HasOne("WarehouseEFApp.Models.Person", "ResponsiblePerson")
                        .WithMany("Warehouses")
                        .HasForeignKey("ResponsiblePersonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("warehouse_responsible_person_id_fkey");

                    b.Navigation("ResponsiblePerson");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Person", b =>
                {
                    b.Navigation("DeliveryDocuments");

                    b.Navigation("ShippingDocuments");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Product", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("TransactionLines");
                });

            modelBuilder.Entity("WarehouseEFApp.Models.Warehouse", b =>
                {
                    b.Navigation("Availabilities");

                    b.Navigation("DeliveryDocuments");

                    b.Navigation("ShippingDocuments");

                    b.Navigation("TransferDocumentReceivingWarehouses");

                    b.Navigation("TransferDocumentSourceWarehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
